### ISSUE TITLE
Tiny profile picture size on the verification page

### ISSUE THREAD

**Issue by goryntsev** [manieer/moodle-block_verify_certificate#7]
The profile picture on the verification page is much smaller than it's showed on the plugin screenshots and than it should be. I think it's due to CSS for .userpicture class that in the theme I use (adaptable) sets the width and height to 35px. It overrides the original dimension 150px in a tag attribute and makes the picture smaller than it's supposed to be. See the attached screenshot for details.
Could you improve it?
![screenshot_certificate_verify](https://cloud.githubusercontent.com/assets/17813303/13729903/e7eaf688-e950-11e5-9ef6-852db9f3ad73.PNG)

**Comment by manieer** [comment]
Hi Alexander Goryntsev,
Thanks for the feedback. I tested this on a few stock themes and they all seem to be displaying the user image at 150px by 150px as intended. I think the problem for you us the adaptable theme. Unfortunately I cannot add a new fix for individual themes as it will mess up for everyone else. Sorry and hope you / your developers will be able to help you fix the issue. 

Regards,
M
