### ISSUE TITLE
Invalid unquoted attribute value

### ISSUE THREAD

**Issue by ewallah** [manieer/moodle-block_verify_certificate#8]
Line 75 of block_line_certificate.php is using a wrong attribute name : id=name="certnumber" 

As a result, some browsers generate unnecessary warnings: Unquoted attribute values should not contain ("), ('), (<), (=), or (`)."

This should be updated to id="???" name="certnumber".

**Comment by manieer** [comment]
Thanks ewallah. I have fixed this and submitted a new version to the plugin db.
